### ISSUE TITLE
[BUG] VisionEmbedding readme example error

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/zeta#100]
In the VisionEmbedding example, run in a colab notebook:

```
ImportError                               Traceback (most recent call last)
[<ipython-input-10-de694ebd704c>](https://localhost:8080/#) in <cell line: 2>()
      1 import torch
----> 2 from zeta.nn import VisionEmbedding
      3 
      4 # Create an instance of VisionEmbedding
      5 vision_embedding = VisionEmbedding(

ImportError: cannot import name 'VisionEmbedding' from 'zeta.nn' (/usr/local/lib/python3.10/dist-packages/zeta/nn/__init__.py)
```

zeta/nn/__init__.py imports 
```
from zeta.nn.embeddings import * 
```
So, I thought the fix was to change the example to:
```
from zeta.nn.embeddings import VisionEmbedding
```
but that doesn't work:
It appears VisionEmbedding isn't exported in zeta.nn.embeddings __init__,py

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/zeta/issues/100">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/zeta/issues/100/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/zeta/issues/100/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@evelynmitchell i think I fixed it lmk

**Comment by evelynmitchell** [comment]
Looks good! Thanks
