### ISSUE TITLE
[BUG]MambaBlock  no working on MacOS, even just import

### ISSUE THREAD

**Issue by eisneim** [kyegomez/zeta#127]
**Describe the bug**
<img width="426" alt="Screenshot 2024-01-27 at 11 08 48" src="https://github.com/kyegomez/zeta/assets/5195894/b3882edb-c9e7-400a-93fb-e7d5d2e38b86">

```
from zeta.nn import MambaBlock

raceback (most recent call last):
  File "/Users/teli/www/ml/SSM/zeta_mamba.py", line 2, in <module>
    from zeta.nn import MambaBlock

RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)
```

**To Reproduce**
use the Readme example

**Expected behavior**
should run simple mamba block

**Screenshots**
<img width="1060" alt="Screenshot 2024-01-27 at 11 09 32" src="https://github.com/kyegomez/zeta/assets/5195894/257ee649-bcec-486e-968c-b1cb0aeeabe3">

**Additional context**

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/zeta/issues/127">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/zeta/issues/127/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/zeta/issues/127/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@eisneim hey can you please submit the full screen shot you missed the error

**Comment by eisneim** [comment]
<img width="1077" alt="Screenshot 2024-01-30 at 10 22 35" src="https://github.com/kyegomez/zeta/assets/5195894/a765a302-12f7-4ac5-bc95-61d48b699b23">
test Palm-E model
<img width="1082" alt="Screenshot 2024-01-30 at 10 22 01" src="https://github.com/kyegomez/zeta/assets/5195894/a47006bb-36c9-4061-a556-c2a8abf49ed1">
@kyegomez  pretty much nothing works, i guess the default datatype on pytorch MPS backend is differient

**Comment by eisneim** [comment]
@kyegomez thank you! it works now 😀👍
