### ISSUE TITLE
Confirm you do not plan to stop spamming people.

### ISSUE THREAD

**Issue by ben-xD** [kyegomez/zeta#15]
Hi @kyegomez, you closed https://github.com/kyegomez/swarms/issues/62 about you spamming people as **"not planned"**. Can you confirm that you do not intent to take any action?

Please take a look at:
- https://www.fcc.gov/general/can-spam
- https://ico.org.uk/for-the-public/online/spam-emails/

## It would be great if you stopped.
![spammer](https://github.com/kyegomez/swarms/assets/24711048/09d989ae-4438-491e-adb2-95f570a1ad96)

Please stop spamming me, and others. Also see https://github.com/kyegomez/swarms/issues/40

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/zeta/issues/15">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/zeta/issues/15/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/zeta/issues/15/pledge.svg">
</picture>
</a>

**Comment by ben-xD** [comment]
I'll close this so we can work on https://github.com/kyegomez/swarms/issues/63

**Comment by eccstartup** [comment]
<img width="1180" alt="image" src="https://github.com/kyegomez/zeta/assets/2290484/4fda0f29-4605-4910-a80d-ec81f9a7d400">
Still spamming me, but the documentation is empty.
<img width="1320" alt="image" src="https://github.com/kyegomez/zeta/assets/2290484/d9ea3d21-45e2-4d97-81dd-9c3d8aead6b2">
