### ISSUE TITLE
[BUG] Running import zeta immediately fails with "RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x4 and 512x512)"

### ISSUE THREAD

**Issue by julian540** [kyegomez/zeta#154]
Hi,

I tried running vision mamba, which relies on zetascale. After following the error stack, I narrowed it down to zetascale causing the problem when trying to import it. 

**To Reproduce**
1. Try running 'import zeta' in Python

**Expected behavior**
For zetascale to be imported and usable

**Screenshots**
![image](https://github.com/kyegomez/zeta/assets/5204969/1de9e8b0-d408-4788-bf61-8f73302cca6e)

**Additional context**
I am working on Ubuntu 22.04, running Python 3.10.13 (I have had the same error with Python 3.9 and 3.11). I have the latest PyTorch as of February 21, 2024. I am working in a Conda virtual environment where I installed vision mamba by running 'pip install vision-mamba' which ran without issues.

I would greatly appreciate any advice on how to zetascale to work!

Thanks,
Julian

**Comment by kyegomez** [comment]
@julian540 I'm closing for now, lmk if you have the issue
