### ISSUE TITLE
[BUG] how could i find a zata version that compatiable with python3.8 and torch 1.12

### ISSUE THREAD

**Issue by renyuanzhe** [kyegomez/zeta#165]
the lastest zata version uses torch2.2

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/zeta/issues/165">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/zeta/issues/165/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/zeta/issues/165/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
Zeta is not compatible with Torch 1.12, why are you using torch 1.12?
