### ISSUE TITLE
[BUG] Torchvision requirement is pinned to 0.18.0

### ISSUE THREAD

**Issue by ClementMaliet** [kyegomez/zeta#232]
**Describe the bug**
Hello,

Although most requirements are lax, the torchvision dependency version is pinned to 0.18.0 which in turns prevents the use of the new PyTorch 2.3.1 version.
I need to use the 2.3.1 version of PyTorch to conform with other dependencies that I have but zeta puts me into a dependency hell. 

Is there any reason to put such a hard pin on torchvision ? 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/zeta/issues/232">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/zeta/issues/232/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/zeta/issues/232/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@ClementMaliet we can change it!

**Comment by kyegomez** [comment]
@ClementMaliet does it work now? Let me know!
