### ISSUE TITLE
Should I use linear layers for the input and output of FlashAttention?

### ISSUE THREAD

**Issue by chenhengx0101** [kyegomez/zeta#247]
I'm curious, do I have to use the linear layer respectively first before I input qkv to FlaskAttention? When I get the output from FlaskAttention, do I still need the linear layer?

I look forward to your reply! Thanks!

**Comment by kyegomez** [comment]
@chelxu the linear projections are already handled inside of the flash attention. You just pass it the inital token embedding and then after that you can use the mlp and then process that an N number of times. 

What are you trying to build!

And, I suggest you join the agora discord for real-time support! 

https://discord.gg/agora-999382051935506503
