### ISSUE TITLE
[Question] Specifying the device to run on

### ISSUE THREAD

**Issue by erlebach** [kyegomez/zeta#288]
I am on a mac, and cannot find where one specifies the device to run on, which in my case is 'mps'. Should I use the standard approach using PyTorch, or is there a more idiomatic approach in zeta? I assume that the library is sufficiently general to run on Nvidia GPUs, ARM GPUs, and the CPU. Thanks.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/zeta/issues/288">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/zeta/issues/288/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/zeta/issues/288/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@erlebach cpu works fine, torch doesn't support m hardware
