### ISSUE TITLE
[BUG] Error in train.py

### ISSUE THREAD

**Issue by erlebach** [kyegomez/zeta#289]
In `train.py`, I see the lines: 
```
    model = model().to(accelerator.device) 
 ```
 This did not work on my mac, because `model()` requires an argument since it calls the `forward` method. 
 The following line works correctly on the mac: 
 ```
     model = model.to(accelerator.device)
 ```
 I do not understand why the code worked at all. Thanks.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/zeta/issues/289">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/zeta/issues/289/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/zeta/issues/289/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@erlebach i don't know what code you're running?
