### ISSUE TITLE
[BUG] no module named zeta

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/zeta#49]
From a container, pytest test/test_init.py:
```
______________________________ ERROR collecting test_init.py _______________________________
ImportError while importing test module '/usr/src/zeta/tests/test_init.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_init.py:1: in <module>
    import zeta
E   ModuleNotFoundError: No module named 'zeta'
```
There is no zeta package to install.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/zeta/issues/49">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/zeta/issues/49/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/zeta/issues/49/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@evelynmitchell you haven't pip installed zetascale, We talked about this

pip3 install zetascale
