### ISSUE TITLE
[TEST] adaptive_rmsnorm - no module named

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/zeta#82]
I looked and the code does contain this module name, and it is in the __init__,py.
```
__________ ERROR collecting tests/nn/modules/test_adaptive_rmsnorm.py __________
ImportError while importing test module '/usr/src/zeta/tests/nn/modules/test_adaptive_rmsnorm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/nn/modules/test_adaptive_rmsnorm.py:3: in <module>
    from zeta.nn.modules.adaptive_rmsnorm import AdaptiveRMSNorm
E   ModuleNotFoundError: No module named 'zeta.nn.modules.adaptive_rmsnorm'

```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/zeta/issues/82">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/zeta/issues/82/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/zeta/issues/82/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@evelynmitchell always remember to upgrde your pip

**Comment by evelynmitchell** [comment]
My pip is up to date.

**Comment by kyegomez** [comment]
@evelynmitchell does this error still exist?

**Comment by evelynmitchell** [comment]
Yes.

```
__________ ERROR collecting tests/nn/modules/test_adaptive_rmsnorm.py __________
ImportError while importing test module '/usr/src/zeta/tests/nn/modules/test_adaptive_rmsnorm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/nn/modules/test_adaptive_rmsnorm.py:3: in <module>
    from zeta.nn.modules.adaptive_rmsnorm import AdaptiveRMSNorm
E   ModuleNotFoundError: No module named 'zeta.nn.modules.adaptive_rmsnorm'
```

**Comment by kyegomez** [comment]
@evelynmitchell upgrade your pip or sync you repo, the problem isn't with the code
