### ISSUE TITLE
[BUG] FusedDenseGELUDense, FusedDropoutLayerNorm not exported in zeta/nn/__init__.py

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/zeta#90]
```
ImportError                               Traceback (most recent call last)
[<ipython-input-11-0b8f0cee3df3>](https://localhost:8080/#) in <cell line: 2>()
      1 import torch
----> 2 from zeta.nn import FusedDenseGELUDense
      3 
      4 x = torch.randn(1, 512)
      5 model = FusedDenseGELUDense(512, 1024)

ImportError: cannot import name 'FusedDenseGELUDense' from 'zeta.nn' (/content/zeta/zeta/nn/__init__.py)
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/zeta/issues/90">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/zeta/issues/90/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/zeta/issues/90/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
the error has been resolved
